#	Copyright 2018, Google LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# [START runtime]
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: dist/virtual-switch-board/\1
  upload: dist/virtual-switch-board/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /(.+)/
  static_files: dist/virtual-switch-board/\1/index.html
  upload: dist/virtual-switch-board/(.+)/index.html

# redirect to 'url + /index.html' url.
- url: /(.+)
  static_files: dist/virtual-switch-board/redirector.html
  upload: dist/virtual-switch-board/redirector.html

# site root
- url: /.*
  static_files: dist/virtual-switch-board/index.html
  upload: dist/virtual-switch-board/index.html
  
- url: /.*
  static_dir: dist/virtual-switch-board  
# [END runtime]